---

- name: Install Scrapy dependencies using yum
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ scrapy_dependencies }}"

- name: Update pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install virtualenv
  pip:
    name: virtualenv
  when: scrapy_in_virtualenv

- name: Install Scrapy
  become: yes
  pip:
    name: scrapy

- name: Install Scrapy
  become: yes
  pip:
    name: scrapy
    virtualenv: "{{ scrapy_virtualenv }}"
  when: scrapy_in_virtualenv

- name: Install extra libraries with pip
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - "{{ scrapy_extra_libraries }}"
